dist: bionic
language: python
python:
  - "3.6"
install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libpcre3-dev libjson-c-dev
script:
  - make
  - LD_LIBRARY_PATH=. LC_ALL=pl_PL.UTF-8 ./declinator 'Jean Babtista Lariron-Święciszewicki'
  - ./test.py |tee testout
  - wc -c < testout |grep '^0$'
