language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - libjson0-dev
      - libpcre3-dev
script:
  - make
  - LD_LIBRARY_PATH=. LC_ALL=pl_PL.UTF-8 ./declinator 'Jean Babtista Lariron-Święciszewicki'
  - ./test.py |tee testout
  - wc -c < testout |grep '^0$'
