language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - debhelper
      - fakeroot
      - automake
      - rpm
      - libpcre3-dev
      - libjson-c-dev
script:
  - export DECLINATOR_VERSION=$(rpm -q --qf '%{v}\n' --specfile declinator.spec|head -1) && echo $DECLINATOR_VERSION
  - mkdir -p ~/rpmbuild/SOURCES && git archive HEAD --prefix=declinator-${DECLINATOR_VERSION}/ | gzip > ~/rpmbuild/SOURCES/v${DECLINATOR_VERSION}.tar.gz
#  - rpm --eval '%GNUconfigure'
  - rpmbuild -ba --nodeps --define='__mydir ${_mydir}' --define='_dr ${dr}' --define='_dirs ${dirs}' --define='_coin ${_coin}' --define='_ACLOCAL_FLAGS ${ACLOCAL_FLAGS}' --define='_k ${k}' --define='_macrodirs ${macrodirs}' --define='_aclocalinclude ${aclocalinclude}' --define 'make_build make %{?_smp_mflags}' --define 'py3_build %{expand:CFLAGS="%{optflags}" python3 setup.py %{?py_setup_args} build --executable="python3 %{?py3_shbang_opts}" %{?*};sleep 1}' --define 'py3_install %{expand:CFLAGS="%{optflags}" python3 setup.py %{?py_setup_args} install -O1 --skip-build --root %{buildroot} %{?*}}' --define 'python3_sitelib %(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")' declinator.spec
