language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - libjson0-dev
      - libpcre3-dev
script:
  - make
  - ./declinator 'Jean Babtista Lariron'
  - ./test.py |tee testout
  - wc -c < testout |grep '^0$'
